name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2022-04-20
version: '9.3.12'
project: 'drupal'
datestamp: 1650467597
