se_bill.settings:
  type: mapping
  label: 'Bill settings'
  mapping:
    vocabulary:
      type: string
      label: 'Taxonomy vocab for bill status.'
    bill_status_term:
      type: string
      label: 'Default term for the default status of an invoice.'
