se_quote.settings:
  type: mapping
  label: 'Quote settings'
  mapping:
    vocabulary:
      type: string
      label: 'Taxonomy vocab for quote status.'
    quote_status_term:
      type: string
      label: 'Default term for the default status of an invoice.'
