name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2022-05-11
version: '9.3.13'
project: 'drupal'
datestamp: 1652261935
