se_purchase_order.settings:
  type: mapping
  label: 'Purchase order settings'
  mapping:
    vocabulary:
      type: string
      label: 'Taxonomy vocab for purchase order status.'
    purchase_order_status_term:
      type: string
      label: 'Default term for the default status of a purchase order.'
